# Generated by Django 4.0.5 on 2022-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('comentario', models.TextField(max_length=200, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/foro')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('comentario', models.TextField(max_length=200, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/foro')),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=20, unique=True, verbose_name='Tema')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('contenido', models.TextField(max_length=200, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/foro')),
            ],
        ),
    ]
