# Generated by Django 4.0.5 on 2022-07-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro_mensajeria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foro'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='posteo_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='foro_mensajeria.posteo'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foro'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foro'),
        ),
    ]
