# Generated by Django 4.0.5 on 2022-07-21 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docentes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursopostulado',
            options={'verbose_name_plural': 'Postulaciones a Cursos'},
        ),
        migrations.AlterField(
            model_name='cursopostulado',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Docentes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
