# Generated by Django 4.0.5 on 2022-07-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_comision_options_comision_final_and_more'),
        ('docentes', '0003_alter_cursopostulado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursopostulado',
            name='curso_postulado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.comision'),
        ),
    ]
