# Generated by Django 4.0.5 on 2022-07-21 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AddField(
            model_name='comision',
            name='final',
            field=models.DateField(null=True, verbose_name='Final'),
        ),
        migrations.AddField(
            model_name='comision',
            name='inicio',
            field=models.DateField(null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='vacantes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Vacantes'),
        ),
    ]
