# Generated by Django 4.0.5 on 2022-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_comision_options_comision_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos_logos', verbose_name='Logo'),
        ),
    ]
